### ISSUE TITLE
SP message: undefined method `split' for nil:NilClass

### ISSUE THREAD

**Issue by mbutz** [repl-electric/sonic-pi.el#10]
Hi Joseph,
`sonic-pi.el` did run without any problems until today. When I jack in, everything seems to be okay, but I seem not to be able to run any script: The SP buffer does not display any messages and nothing is to be heard. 

In the SP server message buffer I get the following message: 

`undefined method split for nil:NilClass`

`C-c k` seems to stop the script, because the SP message buffer displays `Stopping all runs`.

This is seemingly the same problem [William encounters](https://groups.google.com/forum/#!topic/sonic-pi/e6BimXhOtKI).

As I said I ran `sonic-pi.el` before with SP 2.7 #dev without any problems. I did also tried SP 2.8 #dev with the same error as described. Currently using Ubuntu 14.04 (Studio).

Martin

**Comment by wdenton** [comment]
Today when I connect and do M-x sonic-pi-send-buffer, I get:

    sonic-pi-send-buffer: Symbol’s value as variable is void: f

I don't have enough insight to debug the problem further, but I hope it won't be hard to tweak this to go with recent changes in Sonic Pi.

**Comment by wdenton** [comment]
I think `(setq false nil)` as mentioned in #11 fixes this (but that needs a proper fix of its own!)

**Comment by mbutz** [comment]
Yes indeed. It does.

**Comment by josephwilk** [comment]
This was my elisp inexperience. I thought false was a thing. I believe I removed this reference and so should not be an issue. Feel free to re-open if it still is a thing
