### ISSUE TITLE
Support for Sonic Pi 2.10+

### ISSUE THREAD

**Issue by mbutz** [repl-electric/sonic-pi.el#14]
Hi Joseph,

I really do like working with Emacs and Sonic Pi; it's great that you coded this package. Basically it is working but I have some issues and I wonder if you are still maintaining `sonic-pi.el`? Does it make sense to file an issue for `sonic-pi.el` running with Sonic Pi 2.10.

Martin

**Comment by josephwilk** [comment]
Sorry for the delay, I've been using the QT Editor for a good while now but have returned recently to using emacs again.
A couple of bumps and patches and I'm currently running SonicPi master so I would hope it would work with SonicPI 2.10. 
Definitely let me know if you have problems.

**Comment by mbutz** [comment]
Hi Joseph, thanks for answering. I have have - probably - a very simple issue I haven't been able to solve. Since I am using the compiled Debian/Ubuntu package of Sonic Pi (2.10) `sonic-pi.el` complaines with: 

```
Could not find a sonic-pi server in: /usr/bin/sonic-pi/
```
Also `/usr/lib/sonic-pi/` won't do it. Any ideas?

Rg
Martin

**Comment by josephwilk** [comment]
Odd, let me ask the person in charge of the Debian package about setup and see if that helps get to the bottom of it.

**Comment by josephwilk** [comment]
@mbutz I'm running against the master branch so I'm a little off with the debian install.
The key thing is to find where your `sonic-pi-server.rb` file:
For example mine is install here:
`/Users/josephwilk/Workspace/josephwilk/c++/sonic-pi/app/server/bin/sonic-pi-server.rb`

If we can find that we know where to point emacs. 

If it has problems starting the ruby server you can start it yourself (thats pretty much what I do 100% due to development).

Lets see if that helps us move forward.

**Comment by mbutz** [comment]
@josephwilk Found it in:
```
/usr/lib/sonic-pi/server/bin/
```
Unfortunately the adjusted path does not make a difference. After starting `jack`, then Emacs and doing a `sonic-pi-jack-in` it says:
```
Could not find a sonic-pi server in: /usr/lib/sonic-pi/server/bin/
```
I am using Spacemacs since a while. The layer for Sonic Pi has the following config:

```
(defun sonic-pi/init-sonic-pi ()
  (use-package sonic-pi
    :config
    (setq sonic-pi-path "/usr/lib/sonic-pi/server/bin/")
    ))
```
Anything else I should do?

Thanks for looking into it!

**Comment by mbutz** [comment]
Well, I don't know if this sheds some light on my issues:

A `ruby /usr/lib/sonic-pi/server/bin/sonic-pi-server.rb ` gives me (I assume, that is what you meant with 'start it myself', right?):

```
Sonic Pi server booting...
Using protocol: udp
This is Sonic Pi v2.10 running on linux with ruby api 2.3.0.Exception!
Sonic Pi Server successfully booted.

Connection refused - send(2)
["/usr/lib/sonic-pi/server/sonicpi/lib/sonicpi/osc/udp_client.rb:33:in `send'", "/usr/lib/sonic-pi/server/sonicpi/lib/sonicpi/osc/udp_client.rb:33:in `send'", "/usr/lib/sonic-pi/server/bin/sonic-pi-server.rb:340:in `block in <main>'"]
Exception!
```
With GUI Sonic Pi runs flawlessly...

**Comment by josephwilk** [comment]
@mbutz That exception is not too much of a worry. Its just expecting a client to handshake with, as soon as the emacs client connects it would be good. So its a good step forward you can start it ok.

What it sounds to me like is that the validation in https://github.com/repl-electric/sonic-pi.el/blob/master/sonic-pi.el#L66-L68 is incorrectly tripping you up. 

Looking at the source I think what we have is a different install path of the server than on os x.
```
(setq sonic-pi-path "/usr/lib/sonic-pi/server/bin/")
(defvar sonic-pi-server-bin  "app/server/bin/sonic-pi-server.rb")
```

I think the mistake is the `app` part. You don't have that on your install. So if we push that bit to the sonic-pi-path I think we might have a fix.

**Comment by josephwilk** [comment]
@mbutz  My elisp is not strong but I'm guessing if you want a quick fix it would be to redefine the sonic-pi-server-bin var.

Something like (I'm guessing you can refine a `defvar`):
```
(setq sonic-pi-path "/usr/lib/sonic-pi/")
(setq sonic-pi-server-bin "server/bin/sonic-pi-server.rb")
```

**Comment by mbutz** [comment]
Yes! That did the trick. Thanks again for the support!
