### ISSUE TITLE
Could not find a sonic-pi server in sonic-pi-path

### ISSUE THREAD

**Issue by Mestelan** [repl-electric/sonic-pi.el#25]
Hello,

As mentioned in #22, I got this error message when starting sonic-pi-mode:
`Could not find a sonic-pi server in: ~/git_repos/sonic-pi`

Indeed, the path defined by 
`(defvar sonic-pi-server-bin "server/bin/sonic-pi-server.rb")`
does not exist in my checkout of sonic-pi.

I then defined 
`(defvar sonic-pi-server-bin "app/server/ruby/bin/sonic-pi-server.rb")`
which works OK.

Still, wonder whether this should be the default in sonic-pi-mode?

**Comment by Sohalt** [comment]
Anything blocking this @josephwilk ?

**Comment by josephwilk** [comment]
@Sohalt No, just my inability to manage all the things. Merged. Thanks for the reminder.

**Comment by Sohalt** [comment]
Thank you!
