### ISSUE TITLE
Error messages are HTML-escaped

### ISSUE THREAD

**Issue by wdenton** [repl-electric/sonic-pi.el#5]
Thanks for making this! It's wonderful.

I noticed a small issue: when something goes wrong and an error shows in the _sonic-pi-messages_ buffer, it's HTML-escaped, for example:

```
Error: (3 Thread live_loop_ones died: #&lt;NoMethodError: undefined method `/&#39; for &quot;3&quot;:String&gt; eval:21:in `block (2 levels) in __spider_eval&#39;
eval:47:in `block (3 levels) in __spider_eval&#39;
eval:45:in `each&#39;
eval:45:in `block (2 levels) in __spider_eval&#39;
```

That really is:

```
Error: (3 Thread live_loop_ones died: #<NoMethodError: undefined method `/' for "3":String> eval:21:in `block (2 levels) in __spider_eval'
eval:47:in `block (3 levels) in __spider_eval'
eval:45:in `each'
eval:45:in `block (2 levels) in __spider_eval'
```

**Comment by josephwilk** [comment]
Thanks for reporting that. It's something the server is doing, I'll see if I can transform it in emacs

**Comment by josephwilk** [comment]
Yes this is annoying, I'm trying to see if there is a fix that does not bog everything down and add more dependencies. For now I've added a tiny hack until I find something better

**Comment by josephwilk** [comment]
A couple of simple escaping cases have been fixed. Probably needs a more generally solution though.
