### ISSUE TITLE
Connection refused or no sound

### ISSUE THREAD

**Issue by dermusikman** [repl-electric/sonic-pi.el#6]
1. When I perform `sonic-pi-jack-in`, it appears to create a server and handle requests, but I get no sound.
2. Previously, I could start a server and connect with `sonic-pi-connect`, but I get the following error when I evaluate the buffer. Sometimes, sounds can be heard, but the screen flashes and I hear several "error" alerts. If I try to evaluate a loop, emacs is unresponsive until I kill the server.

```
Sonic Pi.app$ ./app/server/native/osx/ruby/bin/ruby app/server/bin/sonic-pi-server.rb 
Ignoring executable-hooks-1.3.2 because its extensions are not built.  Try: gem pristine executable-hooks-1.3.2
Ignoring gem-wrappers-1.2.4 because its extensions are not built.  Try: gem pristine gem-wrappers-1.2.4
Using protocol: UDP
Found 0 LADSPA plugins
Number of Devices: 2
   0 : "Built-in Microph"
   1 : "Built-in Output"

"Built-in Microph" Input Device
   Streams: 1
      0  channels 2

"Built-in Output" Output Device
   Streams: 1
      0  channels 2

SC_AudioDriver: sample rate = 44100.000000, driver's block size = 512
SuperCollider 3 server ready.
PublishPortToRendezvous 0 52241
Exception!
Connection refused - send(2)
["/Volumes/Sonic Pi for Mac v2.2.0/Sonic Pi.app/app/server/core.rb:87:in `send'", "/Volumes/Sonic Pi for Mac v2.2.0/Sonic Pi.app/app/server/core.rb:87:in `send_raw'", "app/server/bin/sonic-pi-server.rb:326:in `block in <main>'"]
^Capp/server/bin/sonic-pi-server.rb:355:in `join': Interrupt
        from app/server/bin/sonic-pi-server.rb:355:in `<main>'
```

The emacs mini-buffer reports `error in process filter: Invalid function: 102`, and debug-mode gives the following:

```
Debugger entered--Lisp error: (invalid-function 102)
  102(1049606881280.0)
  #[(type) "\301^H\302\303 !\304\305 !\306\307 !$\207" [type case 102 osc-read-float32 105 osc-read-int32 115 osc-read-string] 6](115)
  mapcar(#[(type) "\301^H\302\303 !\304\305 !\306\307 !$\207" [type case 102 osc-read-float32 105 osc-read-int32 115 osc-read-string] 6] (115))
  osc-filter(#<process sonic-pi.el OSC server> "/info^@^@^@,s^@^@Starting run 1^@^@")
```

I'm pretty new to emacs, but I get the impression that the sonic-pi-mode process is refusing connection - or failing to properly handle connection - ~~to~~ from the server? I can't determine where that problem may arise, or how to rectify it.

I've tried this with both Sonic Pi 2.2 and 2.3, using SuperCollider 3.6.6 on OSX 10.9.5. Both applications work fine through their GUIs.

**Comment by gberenfield** [comment]
removing *.elc files in the osc package fixed the `error in process filter: Invalid function: 102` errors for me.

HTH,
Greg

**Comment by dermusikman** [comment]
I'm afraid that didn't work :(
Since creating this issue, I've made a vim plugin to serve my needs. I took up emacs only to do this, really.

I'll leave the issue open, as it remains a problem; and I'm happy to offer any assistance I can to resolve it.

If no one else can duplicate my problem, I've no objection to repl-electric closing this issue.
