### ISSUE TITLE
Considerable delay working with emacs vs. sonic pi

### ISSUE THREAD

**Issue by mbutz** [repl-electric/sonic-pi.el#7]
Hi,
this is might rather be a question then an issue. Maybe it's due to my setup but while working with `sonic-pi.el` I encounter a considerable delay even with simple commands like `play :c` compared to working directly within Sonic Pi. 'Considerable' means something like a second before I hear the sound after evaluating the code. Any ideas why this is the case?

This is a too bad because I like working from within Emacs a lot and am very grateful for the good work you did!

I am working with Emacs 24.3.1 on Debian Jessie.
Regards
Martin

**Comment by josephwilk** [comment]
Odd, both Sonicpi and Emacs are sending osc messages to a ruby server. My only thought would be Emacs is taking longer encoding the messages, I'm unsure of c++ vs emacs lisp performance. Both are using udp. 

I'll play around and see if there is any options for faster performance. I've not noticed it being slow on my machine.

**Comment by mbutz** [comment]
Joseph, sorry I did not update this issue. It's gone two plattforms I work with. Actually Sonic Pi does perform better with Emacs compared to the native GUI. And editing is much more what I am used to. So I will close this issue because I do can not reproduce the issue anymore. Thanks for replying.
Martin
