### ISSUE TITLE
highlight now required

### ISSUE THREAD

**Issue by wdenton** [repl-electric/sonic-pi.el#9]
I updated to the new sonic-pi.el package, and then on restart Emacs threw an error because I didn't have the highlight package installed.  Installing it by hand fixed things, but somewhere in there, if highlight is now required, Emacs didn't know.

**Comment by technomancy** [comment]
Please consider making this dependency optional; from what I can tell the `highlight` package is hosted on the EmacsWiki, and it is somewhat irresponsible to encourage users to install software from that source.

**Comment by josephwilk** [comment]
Until a better solution is contribute or developed I've re-added this.
The PR did not have the same behaviour.

**Comment by technomancy** [comment]
Weird; the effect was basically the same. Maybe the faces used by `highlight` have changed in recent versions of Emacs.
